data:
  price_path: data/raw/nvda_prices.csv
  window_days: 120
  macro:
    - path: data/external/fed_funds_rate_macro.csv
      date_column: date
      value_column: value
      alias: fed_funds_rate
    - path: data/external/nvda_sentiment.csv
      date_column: date
      value_column: sentiment_score
      alias: nvda_sentiment
  benchmarks:
    - path: data/raw/benchmarks/spy_prices.csv
      date_column: Date
      value_column: Close
      alias: spy_close

target:
  column: Close
  horizon: 1
  transform: price

feature_engineering:
  lag_features:
    columns: [Close, Volume]
    lags: [1, 2, 3, 5, 10]
  rolling_windows:
    columns: [Close]
    windows: [5, 10, 21]
    statistics: [mean, std]
  technical_indicators:
    rsi:
      column: Close
      window: 14
    macd:
      column: Close
      fast: 12
      slow: 26
      signal: 9
  momentum:
    columns: [Close]
    periods: [1, 5, 10]
  volatility:
    columns: [Close]
    windows: [5, 10, 21]
  bollinger:
    columns: [Close]
    window: 20
    std_multiplier: 2
  volume:
    pct_change_periods: [1, 5]
    rolling_zscore_windows: [10]
  sentiment:
    columns: [nvda_sentiment]
    windows: [5, 10]
    statistics: [mean]
  calendar:
    include: [day_of_week, month]
  benchmark_relations:
    - benchmark: spy_close
      price_column: Close
      feature: relative_return

split:
  method: time_series
  train_ratio: 0.7
  validation_ratio: 0.15
  test_ratio: 0.15

models:
  - name: random_forest
    type: random_forest
    params:
      n_estimators: 500
      max_depth: 8
      min_samples_leaf: 2
      random_state: 42
    search:
      type: grid
      param_grid:
        n_estimators: [400, 500]
        max_depth: [6, 8]
      cv: 3
      n_jobs: 1
  - name: gradient_boosting
    type: gradient_boosting
    params:
      n_estimators: 400
      learning_rate: 0.05
      max_depth: 3
      random_state: 42
    search:
      type: grid
      param_grid:
        n_estimators: [300, 400]
        learning_rate: [0.03, 0.05]
        max_depth: [3, 4]
      cv: 3
      n_jobs: 1

outputs:
  metrics_path: reports/metrics/latest.json
  predictions_path: reports/datasets/latest_predictions.csv
  predictions_full_path: reports/datasets/latest_predictions_full.csv
  predictions_weekly_path: reports/datasets/latest_predictions_weekly.csv
  model_path: trained_models/latest_model.pkl
  plot_path: reports/figures/latest_actual_vs_predicted.html
  plot_weekly_path: reports/figures/latest_actual_vs_predicted_weekly.html
  weekly_weeks: 14
  weekly_freq: W-MON
