# High-level pipeline configuration template.

random_seed: 42

feature_engineering:
  lag_features:
    lags: [1, 2, 3, 5, 10]
  rolling_windows:
    windows: [5, 10, 21]
    statistics: ["mean", "std"]
  technical_indicators:
    - "rsi"
    - "macd"

split:
  method: "time_series"
  train_ratio: 0.7
  validation_ratio: 0.15
  test_ratio: 0.15

model:
  name: "random_forest"
  hyperparameters:
    n_estimators: 500
    max_depth: 8
    min_samples_leaf: 2

evaluation:
  metrics:
    - "rmse"
    - "mape"
    - "directional_accuracy"
  backtest:
    horizons: [1, 5, 21]
